### ISSUE TITLE
Change order CI jobs when merge in master

### ISSUE THREAD

**Issue by danypr92** [coopdevs/timeoverflow-provisioning#152] opened 2020-01-24 09:45 UTC
When we merge a PR in master, a pipeline is run.

This pipeline has 3 jobs, 2 for lint the files and 1 to deploy to staging.

The order now is:

1. Deploy to staging
2. Lints

I think that this order does not have sense, I don't want lint the files after deploy them.

Related links:

CI configuration: https://github.com/coopdevs/timeoverflow-provisioning/blob/master/.travis.yml
Exemple of pipeline with wrong order: https://travis-ci.org/coopdevs/timeoverflow-provisioning/builds/641274628?utm_source=github_status&utm_medium=notification

**Comment by sauloperez** [comment] 2020-03-09 09:54
This is a duplicate of https://github.com/coopdevs/timeoverflow-provisioning/issues/117 so I'm closing this.

**Closed as completed by sauloperez** 2020-03-09 09:54 UTC
